name: Build Deploy Report

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: echo "Project Build Successful"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        run: echo "Project Deployed Successfully"

  report-build-status:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Report Status
        run: echo "Build and Deployment Completed"
